# Generated by Django 3.1.2 on 2020-10-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0002_auto_20201017_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
