# Generated by Django 3.1.2 on 2020-11-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0003_auto_20201017_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photos',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePhoto',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
