# Generated by Django 3.1.2 on 2020-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0004_auto_20201103_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
