# Generated by Django 3.1.2 on 2020-11-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0007_auto_20201103_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePhoto',
            new_name='profile_photo',
        ),
    ]
