# Generated by Django 3.1.2 on 2020-11-04 01:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0010_auto_20201104_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='created',
        ),
        migrations.AddField(
            model_name='chat',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
