# Generated by Django 3.1.2 on 2020-11-04 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0014_auto_20201104_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='request_identity_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_identity_from', to=settings.AUTH_USER_MODEL),
        ),
    ]
