# Generated by Django 3.1.2 on 2020-11-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0015_chatroom_request_identity_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
