# Generated by Django 3.1.2 on 2020-11-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0016_auto_20201104_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='media/assets/default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='media/assets/profile-default.png', upload_to='media/'),
        ),
    ]
