# Generated by Django 3.1.2 on 2020-11-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0017_auto_20201105_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='assets/default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='assets/profile-default.png', upload_to='media/'),
        ),
    ]
