# Generated by Django 3.1.2 on 2020-11-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0018_auto_20201105_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile-default.png', upload_to='media/'),
        ),
    ]
