# Generated by Django 3.1.2 on 2020-11-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0019_auto_20201105_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
