# Generated by Django 3.1.2 on 2020-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0020_auto_20201105_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
