# Generated by Django 3.1.2 on 2020-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0025_auto_20201105_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(default='', max_length=512),
        ),
    ]
