# Generated by Django 3.1.2 on 2020-11-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0026_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(default=''),
        ),
    ]
