# Generated by Django 3.1.2 on 2020-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0028_user_google_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
