# Generated by Django 3.1.2 on 2020-11-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchus', '0029_auto_20201110_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_user_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
